### ISSUE TITLE
Re-design it for KOSS

### ISSUE THREAD

**Issue by proffapt** [kossiitkgp/csv2vcf#1]
## TODO

- [ ] Implement changes for it to be used inside koss. Use fields specific to kosss' contact csv files (Refer [this](https://github.com/kossiitkgp/secrets/blob/master/Contacts/2022.csv))
- [ ] Integrate into secrets repo. Following changes will be required
  - [ ] Plan the specifics for the vcf files, what all data will be used and how it will be used( contact @proffapt ).
  - [ ] The script will be present in `Contacts/scripts`.
  - [ ] Arguments will be set inside the script itself (look at already existing scripts for some basic idea).
  - [ ] All the csv files will be read for changes, if there's a change then only add the entry.
  - [ ] All the vcf files generated will be stored inside `Contacts/vcf` folder.
  - [ ] Add a workflow to execute the script, whenever there's a change in any of the csv files or this script itself (look at already existing workflows)
- [ ] Delete this repository

**Comment by proffapt** [comment]
@harshit-jain52 you can start working on it, create a branch right here in this repository, don't fork it. Ask me on slack or here if you have any doubts or are struggling on something to decide.
